pipeline:
  clean:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      - dotnet clean pangpoc/WebApplication1/WebApplication1/WebApplication1.csproj
   
  build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1.102
    commands:
      - dotnet build pangpoc/WebApplication1/WebApplication1/WebApplication1.csproj
   
