pipeline:
  clean:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      - dotnet clean pangpoc/WebApplication1/WebApplication1/WebApplication1.csproj
   
  build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1.102
    commands:
      - dotnet build pangpoc/WebApplication1/WebApplication1/WebApplication1.csproj
   
  publish:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
    - apt-get update -y
    - apt-get upgrade -y
    - apt-get install zip unzip -y
    - dotnet publish --configuration Release pangpoc/WebApplication1/WebApplication1.sln --output /drone/src/web/
  #- cp -r /drone/src/Impress.UI/bin/Release/netcoreapp2.2/ /drone/src/web/
  #- cp -r /drone/src/Impress.Core/bin/Release/netcoreapp2.2/ /drone/src/web/
    - cd /drone/src/web
    - zip -r output_file.zip *
    - cp -r output_file.zip /drone/src
  
  deploy:
    image: mcr.microsoft.com/azure-cli
      #id: client_id
      #pass: client_password
      #tenant: client_tenant
      #app_web_name: app_web_name
      #app_web_rg: app_web_rg
    commands:
    - az login --service-principal -u $client_id -p $client_password -t $client_tenant
    - az webapp deployment source config-zip --src /drone/src/output_file.zip -n $app_web_name -g $app_web_rg
    secrets: [ client_id, client_password, client_tenant, app_web_name, app_web_rg ]
